name: Deploy CI
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: npm install

      - name: plugins
        run: yarn add umi-plugin-setting-drawer umi-plugin-antd-theme umi-plugin-pro
      - name: fetch-blocks
        run: yarn run pro fetch-blocks
      - name: build
        run: npm run site
      - name: deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTION_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
        with:
          emptyCommits: false
